### ISSUE TITLE
Background Should Be Fixed

### ISSUE THREAD

**Issue by yusufalperendumlu** [harundogdu/twitter-clone#11]
- Arka plan ve yazı rengi yüzünden isimlendirmeler gözükmemekte.

![Screenshot_38](https://user-images.githubusercontent.com/101521433/231804390-9e323535-a9ed-4bbe-8a13-22a62aa5720a.png)
![Screenshot_39](https://user-images.githubusercontent.com/101521433/231804438-33085089-cf34-44df-bf2c-0a7b08a76bab.png)
![Screenshot_40](https://user-images.githubusercontent.com/101521433/231804479-4b430c6f-6e73-4bce-8496-61d41c7171ca.png)

**Comment by harundogdu** [comment]
fixed with #12 @yusufalperendumlu fyi.
