### ISSUE TITLE
E-mail fields validation development for the Login and register pages

### ISSUE THREAD

**Issue by harundogdu** [harundogdu/twitter-clone#16]
- Geçersiz e-mail adresi girildiğinde; 
    - "Login" butonuna veya "Register" butonuna basılamamalı. (disabled olmalı),
     - E-mail'in geçersiz olduğu ile ilgili bir uyarı mesajı gelmeli.

![image](https://user-images.githubusercontent.com/43449361/231904960-b9d20511-53d3-40f9-995b-109c66e98934.png)

**Comment by atahantutar** [comment]
Ben yapabilirim.

**Comment by harundogdu** [comment]
Tabii. Set ediyorum.

**Comment by yusufalperendumlu** [comment]
![Screenshot_52](https://user-images.githubusercontent.com/101521433/235812398-6ea8516d-373f-4ed6-82ce-6387873a2526.png)

- URL link şeklinde eklenilecek.
