### ISSUE TITLE
Title and favicon changes should be made. According to twitter.

### ISSUE THREAD

**Issue by harundogdu** [harundogdu/twitter-clone#17]
-  Anasayfada Title ve favicon değiştirilmeli. (Twitter'dan orijinalleri eklenebilir.)

![image](https://user-images.githubusercontent.com/43449361/231906000-b1198766-293c-469c-b088-2630bc3a3f20.png)

**Comment by atahantutar** [comment]
Bu görevi üstlenmek istiyorum.
