### ISSUE TITLE
Edit will be passed on the bio side

### ISSUE THREAD

**Issue by yusufalperendumlu** [harundogdu/twitter-clone#19]
![Screenshot_44](https://user-images.githubusercontent.com/101521433/234956556-324d9e90-f822-4df3-9c4c-5e4d61fed1c8.png)
 
- Kişinin ne zaman katıldığı, doğum tarihi gibi bilgiler bio da gösterilecek.

**Comment by atahantutar** [comment]
Ben üstlenmek istiyorum.

**Comment by yusufalperendumlu** [comment]
![235812398-6ea8516d-373f-4ed6-82ce-6387873a2526](https://user-images.githubusercontent.com/101521433/236623800-729511c7-7404-4a52-bbbf-66e05cc64249.png)

-URL link şeklinde eklenilecek.
