### ISSUE TITLE
Username will be edited

### ISSUE THREAD

**Issue by yusufalperendumlu** [harundogdu/twitter-clone#32]
![Screenshot_59](https://user-images.githubusercontent.com/101521433/235882435-2e33f7ff-55f9-4eaf-bdee-a7a66d095447.png)

- Kullanıcı adı, kullanıcının sonradan değiştirmesini göz önünde bulundurarak değişiklik yapılabilir bir yapı haline getirilecek.
- Eğer bahsettiğimiz değişiklik sonucu daha önceden kullanılan isim olursa buton yapımız 'Disable' hale getirilecek.

**Comment by harundogdu** [comment]
@yusufalperendumlu bu iş ne durumda?

**Comment by yusufalperendumlu** [comment]
Issue ile ilgilenmeye başladım. Bilginize @harundogdu.
