### ISSUE TITLE
Splash Loading

### ISSUE THREAD

**Issue by yusufalperendumlu** [harundogdu/twitter-clone#9]
![Screenshot_36](https://user-images.githubusercontent.com/101521433/230735906-3cecbc4b-6a20-4968-a922-b0be7733fa2d.png)

-This type of login screen will be created

**Comment by harundogdu** [comment]
@yusufalperendumlu bu geliştirme ne durumda?

**Comment by yusufalperendumlu** [comment]
@harundogdu mesajınızı yeni görüp olup, issuenun tamamlandığını bildirmek isterim.
